export const SCREENS = {
    registration: 'Registration',
    onboarding: 'Onboarding',
    preregistration: 'PreRegistration',
    login: 'Login',
    home: 'Home',
    profile: 'Profile',
    about: 'About',
    customerservice: 'Customer Service',
    history: 'History',
    reportleakage: 'Report Leakage',
    chat: 'Chat',
    documents: 'Documents',
    buywater: 'BuyWater',
    payment: 'Payment',
    cardentry: 'Card Entry',
    paymentsuccess: 'Payment Success',
};
